<?php

use Illuminate\Database\Seeder;

use App\MultiLanguage;

class MultiLanguageSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $datas = [
            // for menu page
			1 => [
                'page_master_id' => 1,
                'language_id' => 1,
                'keyword' => 'dashboard',
                'value' => 'dashboard',
                'created_by' => 1,
            ],2 => [
                'page_master_id' => 1,
                'language_id' => 1,
                'keyword' => 'appointments',
                'value' => 'appointments',
                'created_by' => 1,
            ],3 => [
                'page_master_id' => 1,
                'language_id' => 1,
                'keyword' => 'specialization',
                'value' => 'specialization',
                'created_by' => 1,
            ],4 => [
                'page_master_id' => 1,
                'language_id' => 1,
                'keyword' => 'doctors',
                'value' => 'doctors',
                'created_by' => 1,
            ],5 => [
                'page_master_id' => 1,
                'language_id' => 1,
                'keyword' => 'patients',
                'value' => 'patients',
                'created_by' => 1,
            ],6 => [
                'page_master_id' => 1,
                'language_id' => 1,
                'keyword' => 'payment_requests',
                'value' => 'payment requests',
                'created_by' => 1,
            ],7 => [
                'page_master_id' => 1,
                'language_id' => 1,
                'keyword' => 'settings',
                'value' => 'settings',
                'created_by' => 1,
            ],8 => [
                'page_master_id' => 1,
                'language_id' => 1,
                'keyword' => 'email_template',
                'value' => 'email template',
                'created_by' => 1,
            ],9 => [
                'page_master_id' => 1,
                'language_id' => 1,
                'keyword' => 'cms',
                'value' => 'cms',
                'created_by' => 1,
            ],10 => [
                'page_master_id' => 1,
                'language_id' => 1,
                'keyword' => 'language',
                'value' => 'language',
                'created_by' => 1,
            ],11 => [
                'page_master_id' => 1,
                'language_id' => 1,
                'keyword' => 'my_profile',
                'value' => 'my profile',
                'created_by' => 1,
            ],12 => [
                'page_master_id' => 1,
                'language_id' => 1,
                'keyword' => 'change_password',
                'value' => 'change password',
                'created_by' => 1,
            ],13 => [
                'page_master_id' => 1,
                'language_id' => 1,
                'keyword' => 'logout',
                'value' => 'logout',
                'created_by' => 1,
            ],14 => [
                'page_master_id' => 1,
                'language_id' => 1,
                'keyword' => 'my_patients',
                'value' => 'my patients',
                'created_by' => 1,
            ],15 => [
                'page_master_id' => 1,
                'language_id' => 1,
                'keyword' => 'schedule_timings',
                'value' => 'schedule timings',
                'created_by' => 1,
            ],16 => [
                'page_master_id' => 1,
                'language_id' => 1,
                'keyword' => 'calendar',
                'value' => 'calendar',
                'created_by' => 1,
            ],17 => [
                'page_master_id' => 1,
                'language_id' => 1,
                'keyword' => 'invoice',
                'value' => 'invoice',
                'created_by' => 1,
            ],18 => [
                'page_master_id' => 1,
                'language_id' => 1,
                'keyword' => 'accounts',
                'value' => 'accounts',
                'created_by' => 1,
            ],19 => [
                'page_master_id' => 1,
                'language_id' => 1,
                'keyword' => 'reviews',
                'value' => 'reviews',
                'created_by' => 1,
            ],20 => [
                'page_master_id' => 1,
                'language_id' => 1,
                'keyword' => 'chat',
                'value' => 'chat',
                'created_by' => 1,
            ],21 => [
                'page_master_id' => 1,
                'language_id' => 1,
                'keyword' => 'social_media',
                'value' => 'social media',
                'created_by' => 1,
            ],22 => [
                'page_master_id' => 1,
                'language_id' => 1,
                'keyword' => 'patient_search',
                'value' => 'patient search',
                'created_by' => 1,
            ],23 => [
                'page_master_id' => 1,
                'language_id' => 1,
                'keyword' => 'favourite_doctor',
                'value' => 'favourite doctor',
                'created_by' => 1,
            ],24 => [
                'page_master_id' => 1,
                'language_id' => 1,
                'keyword' => 'doctor_search',
                'value' => 'doctor search',
                'created_by' => 1,
            ],25 => [
                'page_master_id' => 2,
                'language_id' => 1,
                'keyword' => 'contact',
                'value' => 'Contact',
                'created_by' => 1,
            ],26 => [
                'page_master_id' => 2,
                'language_id' => 1,
                'keyword' => 'signin_signup',
                'value' => 'SIGNIN / SIGNUP',
                'created_by' => 1,
            ],27 => [
                'page_master_id' => 2,
                'language_id' => 1,
                'keyword' => 'search_location',
                'value' => 'Search Location',
                'created_by' => 1,
            ],28 => [
                'page_master_id' => 2,
                'language_id' => 1,
                'keyword' => 'search_doctors_diseases_etc',
                'value' => 'Search Doctors, Diseases, Etc',
                'created_by' => 1,
            ],29 => [
                'page_master_id' => 2,
                'language_id' => 1,
                'keyword' => 'based_on_your_location',
                'value' => 'Based on Your Location',
                'created_by' => 1,
            ],30 => [
                'page_master_id' => 2,
                'language_id' => 1,
                'keyword' => 'ex_dental_or_sugar_checkup_etc',
                'value' => 'Ex : Dental or Sugar Check up etc',
                'created_by' => 1,
            ],31 => [
                'page_master_id' => 2,
                'language_id' => 1,
                'keyword' => 'visit_a_doctor',
                'value' => 'Visit a Doctor',
                'created_by' => 1,
            ],32 => [
                'page_master_id' => 2,
                'language_id' => 1,
                'keyword' => 'book_now',
                'value' => 'Book Now',
                'created_by' => 1,
            ],33 => [
                'page_master_id' => 2,
                'language_id' => 1,
                'keyword' => 'find_a_pharmacy',
                'value' => 'Find a Pharmacy',
                'created_by' => 1,
            ],34 => [
                'page_master_id' => 2,
                'language_id' => 1,
                'keyword' => 'find_now',
                'value' => 'Find Now',
                'created_by' => 1,
            ],35 => [
                'page_master_id' => 2,
                'language_id' => 1,
                'keyword' => 'find_a_lab',
                'value' => 'Find a Lab',
                'created_by' => 1,
            ],36 => [
                'page_master_id' => 2,
                'language_id' => 1,
                'keyword' => 'coming_soon',
                'value' => 'Coming Soon',
                'created_by' => 1,
            ],37 => [
                'page_master_id' => 2,
                'language_id' => 1,
                'keyword' => 'free',
                'value' => 'Free',
                'created_by' => 1,
            ],38 => [
                'page_master_id' => 2,
                'language_id' => 1,
                'keyword' => 'view_profile',
                'value' => 'View Profile',
                'created_by' => 1,
            ],39 => [
                'page_master_id' => 2,
                'language_id' => 1,
                'keyword' => 'coming_soon',
                'value' => 'Coming Soon',
                'created_by' => 1,
            ],40 => [
                'page_master_id' => 2,
                'language_id' => 1,
                'keyword' => 'view_all',
                'value' => 'View All',
                'created_by' => 1,
            ],41 => [
                'page_master_id' => 3,
                'language_id' => 1,
                'keyword' => 'home',
                'value' => 'Home',
                'created_by' => 1,
            ],42 => [
                'page_master_id' => 3,
                'language_id' => 1,
                'keyword' => 'doctor_search',
                'value' => 'Doctor Search',
                'created_by' => 1,
            ],43 => [
                'page_master_id' => 3,
                'language_id' => 1,
                'keyword' => 'matches_for_your_search',
                'value' => 'Matches For Your Search',
                'created_by' => 1,
            ],44 => [
                'page_master_id' => 3,
                'language_id' => 1,
                'keyword' => 'search_filter',
                'value' => 'Search Filter',
                'created_by' => 1,
            ],45 => [
                'page_master_id' => 3,
                'language_id' => 1,
                'keyword' => 'reset',
                'value' => 'Reset',
                'created_by' => 1,
            ],46 => [
                'page_master_id' => 3,
                'language_id' => 1,
                'keyword' => 'keywords',
                'value' => 'Keywords',
                'created_by' => 1,
            ],47 => [
                'page_master_id' => 3,
                'language_id' => 1,
                'keyword' => 'gender',
                'value' => 'Gender',
                'created_by' => 1,
            ],48 => [
                'page_master_id' => 3,
                'language_id' => 1,
                'keyword' => 'male_doctor',
                'value' => 'Male Doctor',
                'created_by' => 1,
            ],49 => [
                'page_master_id' => 3,
                'language_id' => 1,
                'keyword' => 'female_doctor',
                'value' => 'Female Doctor',
                'created_by' => 1,
            ],50 => [
                'page_master_id' => 3,
                'language_id' => 1,
                'keyword' => 'select_specialist',
                'value' => 'Select Specialist',
                'created_by' => 1,
            ],51 => [
                'page_master_id' => 3,
                'language_id' => 1,
                'keyword' => 'select_country',
                'value' => 'Select Country',
                'created_by' => 1,
            ],52 => [
                'page_master_id' => 3,
                'language_id' => 1,
                'keyword' => 'select_city',
                'value' => 'Select City',
                'created_by' => 1,
            ],53 => [
                'page_master_id' => 3,
                'language_id' => 1,
                'keyword' => 'select_state',
                'value' => 'Select State',
                'created_by' => 1,
            ],54 => [
                'page_master_id' => 3,
                'language_id' => 1,
                'keyword' => 'search',
                'value' => 'Search',
                'created_by' => 1,
            ],55 => [
                'page_master_id' => 3,
                'language_id' => 1,
                'keyword' => 'feedback',
                'value' => 'Feedback',
                'created_by' => 1,
            ],56 => [
                'page_master_id' => 3,
                'language_id' => 1,
                'keyword' => 'view_profile',
                'value' => 'View Profile',
                'created_by' => 1,
            ],57 => [
                'page_master_id' => 3,
                'language_id' => 1,
                'keyword' => 'Book Appointment',
                'value' => 'Book Appointment',
                'created_by' => 1,
            ],58 => [
                'page_master_id' => 3,
                'language_id' => 1,
                'keyword' => 'sort_by',
                'value' => 'Sort By',
                'created_by' => 1,
            ],59 => [
                'page_master_id' => 3,
                'language_id' => 1,
                'keyword' => 'select',
                'value' => 'Select',
                'created_by' => 1,
            ],60 => [
                'page_master_id' => 3,
                'language_id' => 1,
                'keyword' => 'rating',
                'value' => 'Rating',
                'created_by' => 1,
            ],61 => [
                'page_master_id' => 3,
                'language_id' => 1,
                'keyword' => 'latest',
                'value' => 'Latest',
                'created_by' => 1,
            ],62 => [
                'page_master_id' => 3,
                'language_id' => 1,
                'keyword' => 'free',
                'value' => 'Free',
                'created_by' => 1,
            ],63 => [
                'page_master_id' => 4,
                'language_id' => 1,
                'keyword' => 'home',
                'value' => 'Home',
                'created_by' => 1,
            ],64 => [
                'page_master_id' => 4,
                'language_id' => 1,
                'keyword' => 'doctor_profile',
                'value' => 'Doctor Profile',
                'created_by' => 1,
            ],65 => [
                'page_master_id' => 4,
                'language_id' => 1,
                'keyword' => 'get_directions',
                'value' => 'Get Directions',
                'created_by' => 1,
            ],66 => [
                'page_master_id' => 4,
                'language_id' => 1,
                'keyword' => 'per_slot',
                'value' => 'per slot',
                'created_by' => 1,
            ],67 => [
                'page_master_id' => 4,
                'language_id' => 1,
                'keyword' => 'book_appointment',
                'value' => 'Book Appointment',
                'created_by' => 1,
            ],68 => [
                'page_master_id' => 4,
                'language_id' => 1,
                'keyword' => 'overview',
                'value' => 'Overview',
                'created_by' => 1,
            ],69 => [
                'page_master_id' => 4,
                'language_id' => 1,
                'keyword' => 'locations',
                'value' => 'Locations',
                'created_by' => 1,
            ],70 => [
                'page_master_id' => 4,
                'language_id' => 1,
                'keyword' => 'review',
                'value' => 'Reviews',
                'created_by' => 1,
            ],71 => [
                'page_master_id' => 4,
                'language_id' => 1,
                'keyword' => 'business_hour',
                'value' => 'Business Hour',
                'created_by' => 1,
            ],72 => [
                'page_master_id' => 4,
                'language_id' => 1,
                'keyword' => 'about_me',
                'value' => 'About Me',
                'created_by' => 1,
            ],73 => [
                'page_master_id' => 4,
                'language_id' => 1,
                'keyword' => 'education',
                'value' => 'Education',
                'created_by' => 1,
            ],74 => [
                'page_master_id' => 4,
                'language_id' => 1,
                'keyword' => 'services',
                'value' => 'Services',
                'created_by' => 1,
            ],75 => [
                'page_master_id' => 4,
                'language_id' => 1,
                'keyword' => 'specializations',
                'value' => 'Specializations',
                'created_by' => 1,
            ],76 => [
                'page_master_id' => 4,
                'language_id' => 1,
                'keyword' => 'reviewed',
                'value' => 'Reviewed',
                'created_by' => 1,
            ],77 => [
                'page_master_id' => 4,
                'language_id' => 1,
                'keyword' => 'replied',
                'value' => 'Replied',
                'created_by' => 1,
            ],78 => [
                'page_master_id' => 4,
                'language_id' => 1,
                'keyword' => 'closed',
                'value' => 'Closed',
                'created_by' => 1,
            ],79 => [
                'page_master_id' => 4,
                'language_id' => 1,
                'keyword' => 'holiday',
                'value' => 'Holiday',
                'created_by' => 1,
            ],80 => [
                'page_master_id' => 4,
                'language_id' => 1,
                'keyword' => 'login_doccure',
                'value' => 'Login Doccure',
                'created_by' => 1,
            ],81 => [
                'page_master_id' => 4,
                'language_id' => 1,
                'keyword' => 'email_mobile_number',
                'value' => 'Email or Mobile Number',
                'created_by' => 1,
            ],82 => [
                'page_master_id' => 4,
                'language_id' => 1,
                'keyword' => 'please_enter_email',
                'value' => 'Please Enter Email',
                'created_by' => 1,
            ],83 => [
                'page_master_id' => 4,
                'language_id' => 1,
                'keyword' => 'password',
                'value' => 'Password',
                'created_by' => 1,
            ],84 => [
                'page_master_id' => 4,
                'language_id' => 1,
                'keyword' => 'please_enter_password',
                'value' => 'Please Enter Password',
                'created_by' => 1,
            ],85 => [
                'page_master_id' => 4,
                'language_id' => 1,
                'keyword' => 'forgot_password',
                'value' => 'Forgot Password',
                'created_by' => 1,
            ],86 => [
                'page_master_id' => 4,
                'language_id' => 1,
                'keyword' => 'signin',
                'value' => 'Signin',
                'created_by' => 1,
            ],87 => [
                'page_master_id' => 4,
                'language_id' => 1,
                'keyword' => 'dont_have_an_account',
                'value' => "Don't have an account ?" ,
                'created_by' => 1,
            ],88 => [
                'page_master_id' => 4,
                'language_id' => 1,
                'keyword' => 'register',
                'value' => 'Register',
                'created_by' => 1,
            ],89 => [
                'page_master_id' => 5,
                'language_id' => 1,
                'keyword' => 'patient',
                'value' => 'Patient',
                'created_by' => 1,
            ],90 => [
                'page_master_id' => 5,
                'language_id' => 1,
                'keyword' => 'doctor',
                'value' => 'Doctor',
                'created_by' => 1,
            ],91 => [
                'page_master_id' => 5,
                'language_id' => 1,
                'keyword' => 'first_name',
                'value' => 'First Name',
                'created_by' => 1,
            ],92 => [
                'page_master_id' => 5,
                'language_id' => 1,
                'keyword' => 'last_name',
                'value' => 'Last Name',
                'created_by' => 1,
            ],93 => [
                'page_master_id' => 5,
                'language_id' => 1,
                'keyword' => 'email',
                'value' => 'Email',
                'created_by' => 1,
            ],94 => [
                'page_master_id' => 5,
                'language_id' => 1,
                'keyword' => 'mobile_number',
                'value' => 'Mobile Number',
                'created_by' => 1,
            ],95 => [
                'page_master_id' => 5,
                'language_id' => 1,
                'keyword' => 'password',
                'value' => 'Password',
                'created_by' => 1,
            ],96 => [
                'page_master_id' => 5,
                'language_id' => 1,
                'keyword' => 'confirm_password',
                'value' => 'Confirm Password',
                'created_by' => 1,
            ],97 => [
                'page_master_id' => 5,
                'language_id' => 1,
                'keyword' => 'already_have_an_account',
                'value' => 'Already have an account ?',
                'created_by' => 1,
            ],98 => [
                'page_master_id' => 5,
                'language_id' => 1,
                'keyword' => 'signup',
                'value' => 'SignUp',
                'created_by' => 1,
            ],99 => [
                'page_master_id' => 5,
                'language_id' => 1,
                'keyword' => 'please_enter_your_first_name',
                'value' => 'Please enter your first name',
                'created_by' => 1,
            ],100 => [
                'page_master_id' => 5,
                'language_id' => 1,
                'keyword' => 'please_enter_your_last_name',
                'value' => 'Please enter your last name',
                'created_by' => 1,
            ],101 => [
                'page_master_id' => 5,
                'language_id' => 1,
                'keyword' => 'please_enter_your_email',
                'value' => 'Please enter your email',
                'created_by' => 1,
            ],102 => [
                'page_master_id' => 5,
                'language_id' => 1,
                'keyword' => 'please_enter_your_mobile_number',
                'value' => 'Please enter your mobile number',
                'created_by' => 1,
            ],103 => [
                'page_master_id' => 5,
                'language_id' => 1,
                'keyword' => 'please_enter_your_password',
                'value' => 'Please enter your Password',
                'created_by' => 1,
            ],104 => [
                'page_master_id' => 5,
                'language_id' => 1,
                'keyword' => 'please_enter_your_confirm_password',
                'value' => 'Please enter your confirm password',
                'created_by' => 1,
            ],105 => [
                'page_master_id' => 5,
                'language_id' => 1,
                'keyword' => 'please_enter_your_confirm_password',
                'value' => 'Please enter your confirm password',
                'created_by' => 1,
            ],106 => [
                'page_master_id' => 6,
                'language_id' => 1,
                'keyword' => 'forgot_password',
                'value' => 'Forgot Password ?',
                'created_by' => 1,
            ],107 => [
                'page_master_id' => 6,
                'language_id' => 1,
                'keyword' => 'enter_your_email_to_get_a_password_reset_link',
                'value' => 'Enter your email to get a password reset link',
                'created_by' => 1,
            ],108 => [
                'page_master_id' => 6,
                'language_id' => 1,
                'keyword' => 'email',
                'value' => 'Email',
                'created_by' => 1,
            ],
            // for menu page end
        ];
        foreach ($datas as $id => $data) {
            $row = MultiLanguage::firstOrNew([
                'id' => $id,
            ]);
            $row->fill($data);
            $row->save();
        }
    }
}
